//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XData.Data.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Glossary {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Glossary() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("XData.Data.Resources.Glossary", typeof(Glossary).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Annotation.
        /// </summary>
        internal static string Annotation {
            get {
                return ResourceManager.GetString("Annotation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Annotations.
        /// </summary>
        internal static string Annotations {
            get {
                return ResourceManager.GetString("Annotations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Column.
        /// </summary>
        internal static string Column {
            get {
                return ResourceManager.GetString("Column", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ConfigVersion.
        /// </summary>
        internal static string ConfigVersion {
            get {
                return ResourceManager.GetString("ConfigVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DatabaseKey.
        /// </summary>
        internal static string DatabaseKey {
            get {
                return ResourceManager.GetString("DatabaseKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DatabaseVersion.
        /// </summary>
        internal static string DatabaseVersion {
            get {
                return ResourceManager.GetString("DatabaseVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accept.
        /// </summary>
        internal static string DeletedByOtherUsersHandlerAccept {
            get {
                return ResourceManager.GetString("DeletedByOtherUsersHandlerAccept", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reinsert.
        /// </summary>
        internal static string DeletedByOtherUsersHandlerReinsert {
            get {
                return ResourceManager.GetString("DeletedByOtherUsersHandlerReinsert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ThrowException.
        /// </summary>
        internal static string DeletedByOtherUsersHandlerThrowException {
            get {
                return ResourceManager.GetString("DeletedByOtherUsersHandlerThrowException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Element.
        /// </summary>
        internal static string Element {
            get {
                return ResourceManager.GetString("Element", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Elements.
        /// </summary>
        internal static string Elements {
            get {
                return ResourceManager.GetString("Elements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field.
        /// </summary>
        internal static string Field {
            get {
                return ResourceManager.GetString("Field", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fields.
        /// </summary>
        internal static string Fields {
            get {
                return ResourceManager.GetString("Fields", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accept.
        /// </summary>
        internal static string InsertedByOtherUsersHandlerAccept {
            get {
                return ResourceManager.GetString("InsertedByOtherUsersHandlerAccept", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ForceDelete.
        /// </summary>
        internal static string InsertedByOtherUsersHandlerForceDelete {
            get {
                return ResourceManager.GetString("InsertedByOtherUsersHandlerForceDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ThrowException.
        /// </summary>
        internal static string InsertedByOtherUsersHandlerThrowException {
            get {
                return ResourceManager.GetString("InsertedByOtherUsersHandlerThrowException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NameMapVersion.
        /// </summary>
        internal static string NameMapVersion {
            get {
                return ResourceManager.GetString("NameMapVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prime.
        /// </summary>
        internal static string Prime {
            get {
                return ResourceManager.GetString("Prime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ReferencePath.
        /// </summary>
        internal static string ReferencePath {
            get {
                return ResourceManager.GetString("ReferencePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Relationship.
        /// </summary>
        internal static string Relationship {
            get {
                return ResourceManager.GetString("Relationship", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Content.
        /// </summary>
        internal static string RelationshipContent {
            get {
                return ResourceManager.GetString("RelationshipContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From.
        /// </summary>
        internal static string RelationshipFrom {
            get {
                return ResourceManager.GetString("RelationshipFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RelationshipPath.
        /// </summary>
        internal static string RelationshipPath {
            get {
                return ResourceManager.GetString("RelationshipPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To.
        /// </summary>
        internal static string RelationshipTo {
            get {
                return ResourceManager.GetString("RelationshipTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        internal static string RelationshipType {
            get {
                return ResourceManager.GetString("RelationshipType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove.
        /// </summary>
        internal static string Remove {
            get {
                return ResourceManager.GetString("Remove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version.
        /// </summary>
        internal static string SchemaVersion {
            get {
                return ResourceManager.GetString("SchemaVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sequence.
        /// </summary>
        internal static string Sequence {
            get {
                return ResourceManager.GetString("Sequence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SequenceName.
        /// </summary>
        internal static string SequenceName {
            get {
                return ResourceManager.GetString("SequenceName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set.
        /// </summary>
        internal static string Set {
            get {
                return ResourceManager.GetString("Set", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SetOf.
        /// </summary>
        internal static string SetPrefix {
            get {
                return ResourceManager.GetString("SetPrefix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Table.
        /// </summary>
        internal static string Table {
            get {
                return ResourceManager.GetString("Table", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TableType.
        /// </summary>
        internal static string TableType {
            get {
                return ResourceManager.GetString("TableType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TimezoneOffset.
        /// </summary>
        internal static string TimezoneOffset {
            get {
                return ResourceManager.GetString("TimezoneOffset", resourceCulture);
            }
        }
    }
}
