//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18063
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XData.Data.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("XData.Data.Resources.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ConcurrencyCheck failed..
        /// </summary>
        internal static string ConcurrencyCheck_Failed {
            get {
                return ResourceManager.GetString("ConcurrencyCheck_Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;ConfigVersion&quot; is null or empty..
        /// </summary>
        internal static string ConfigSchema_Version_IsNullOrEmpty {
            get {
                return ResourceManager.GetString("ConfigSchema_Version_IsNullOrEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Version&quot; does not match Database..
        /// </summary>
        internal static string DatabaseConfig_Not_Match_DatabaseVersion {
            get {
                return ResourceManager.GetString("DatabaseConfig_Not_Match_DatabaseVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Version&quot; does not match NameMap..
        /// </summary>
        internal static string DatabaseConfig_Not_Match_NameMap {
            get {
                return ResourceManager.GetString("DatabaseConfig_Not_Match_NameMap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specify Priority to below Relationships:.
        /// </summary>
        internal static string Draft_Specify_Relationships_Priority {
            get {
                return ResourceManager.GetString("Draft_Specify_Relationships_Priority", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duplicate rows have been found in Original by the key &quot;{0}&quot;.
        /// </summary>
        internal static string Duplicate_Original_Found {
            get {
                return ResourceManager.GetString("Duplicate_Original_Found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only one prime ReferencePath should be specified for {0} and {1}..
        /// </summary>
        internal static string Duplicate_PrimeReferencePath {
            get {
                return ResourceManager.GetString("Duplicate_PrimeReferencePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only one prime Relationship should be specified for {0} and {1}..
        /// </summary>
        internal static string Duplicate_PrimeRelationship {
            get {
                return ResourceManager.GetString("Duplicate_PrimeRelationship", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duplicate name in ReationshipPaths of {0} and {1}..
        /// </summary>
        internal static string Duplicate_ReferencePath_Name {
            get {
                return ResourceManager.GetString("Duplicate_ReferencePath_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duplicate ReferencePaths between {0} and {1}..
        /// </summary>
        internal static string Duplicate_ReferencePaths {
            get {
                return ResourceManager.GetString("Duplicate_ReferencePaths", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;FromTo&quot; does not match &quot;Content&quot;..
        /// </summary>
        internal static string FromTo_Not_Match_Content {
            get {
                return ResourceManager.GetString("FromTo_Not_Match_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;{0}&quot; is not a Boolean value..
        /// </summary>
        internal static string Is_Not_Boolean {
            get {
                return ResourceManager.GetString("Is_Not_Boolean", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Name&quot; is null or empty..
        /// </summary>
        internal static string Name_IsNullOrEmpty {
            get {
                return ResourceManager.GetString("Name_IsNullOrEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Version&quot; is null or empty..
        /// </summary>
        internal static string NamedConfig_Name_IsNullOrEmpty {
            get {
                return ResourceManager.GetString("NamedConfig_Name_IsNullOrEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Name&quot; does not match Config..
        /// </summary>
        internal static string NamedConfig_Not_Match_Name {
            get {
                return ResourceManager.GetString("NamedConfig_Not_Match_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Version&quot; does not match primary version..
        /// </summary>
        internal static string NamedConfig_Not_Match_PrimaryVersion {
            get {
                return ResourceManager.GetString("NamedConfig_Not_Match_PrimaryVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Version&quot; does not match Config..
        /// </summary>
        internal static string NamedConfig_Version_Not_Match_Config {
            get {
                return ResourceManager.GetString("NamedConfig_Version_Not_Match_Config", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;NamedConfigVersion&quot; is null or empty..
        /// </summary>
        internal static string NamedConfigVersion_IsNullOrEmpty {
            get {
                return ResourceManager.GetString("NamedConfigVersion_IsNullOrEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The schema &quot;{0}{1}&quot; verify failed..
        /// </summary>
        internal static string NamedSchema_Verification_Failed {
            get {
                return ResourceManager.GetString("NamedSchema_Verification_Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;NameMapVersion&quot; does not match Argument..
        /// </summary>
        internal static string NameMap_NameMapVersion_Not_Match_Argument {
            get {
                return ResourceManager.GetString("NameMap_NameMapVersion_Not_Match_Argument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Version&quot; does not match Database..
        /// </summary>
        internal static string NameMap_Not_Match_DatabaseVersion {
            get {
                return ResourceManager.GetString("NameMap_Not_Match_DatabaseVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Version&quot; is null or empty..
        /// </summary>
        internal static string NameMap_Version_IsNullOrEmpty {
            get {
                return ResourceManager.GetString("NameMap_Version_IsNullOrEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Version&quot; does not match Config..
        /// </summary>
        internal static string NameMap_Version_Not_Match_Config {
            get {
                return ResourceManager.GetString("NameMap_Version_Not_Match_Config", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None of relationships is available between {0} and {1}..
        /// </summary>
        internal static string No_Available_Relationship {
            get {
                return ResourceManager.GetString("No_Available_Relationship", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} can not be found in original..
        /// </summary>
        internal static string Not_Found_Original {
            get {
                return ResourceManager.GetString("Not_Found_Original", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;{0}&quot; is not a SimpleRelationship..
        /// </summary>
        internal static string Not_SimpleRelationship {
            get {
                return ResourceManager.GetString("Not_SimpleRelationship", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;ConfigVersion&quot; does not match Argument..
        /// </summary>
        internal static string PrimaryConfig_ConfigVersion_Not_Match_Argument {
            get {
                return ResourceManager.GetString("PrimaryConfig_ConfigVersion_Not_Match_Argument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Version&quot; does not match Database..
        /// </summary>
        internal static string PrimaryConfig_Not_Match_DatabaseVersion {
            get {
                return ResourceManager.GetString("PrimaryConfig_Not_Match_DatabaseVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Version&quot; does not match NameMap..
        /// </summary>
        internal static string PrimaryConfig_Not_Match_NameMap {
            get {
                return ResourceManager.GetString("PrimaryConfig_Not_Match_NameMap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;PrimaryConfigVersion&quot; does not match Config..
        /// </summary>
        internal static string PrimaryConfig_Version_Not_Match_Config {
            get {
                return ResourceManager.GetString("PrimaryConfig_Version_Not_Match_Config", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The schema: {0} verify failed..
        /// </summary>
        internal static string PrimarySchema_Verify_Failed {
            get {
                return ResourceManager.GetString("PrimarySchema_Verify_Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prime ReferencePath is not be specified for {0} and {1}..
        /// </summary>
        internal static string PrimeReferencePath_Not_Specified {
            get {
                return ResourceManager.GetString("PrimeReferencePath_Not_Specified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prime Relationship is not be specified for {0} and {1}..
        /// </summary>
        internal static string PrimeRelationship_Not_Specified {
            get {
                return ResourceManager.GetString("PrimeRelationship_Not_Specified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Relationships non-connected..
        /// </summary>
        internal static string Relationships_Non_Connected {
            get {
                return ResourceManager.GetString("Relationships_Non_Connected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value of Timestamp field have not been provided..
        /// </summary>
        internal static string Timestamp_IsNullOrEmpty {
            get {
                return ResourceManager.GetString("Timestamp_IsNullOrEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TimestampCheck failed..
        /// </summary>
        internal static string TimestampCheck_Failed {
            get {
                return ResourceManager.GetString("TimestampCheck_Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Type&quot; is not match {0}..
        /// </summary>
        internal static string Type_Not_Match_Relationship {
            get {
                return ResourceManager.GetString("Type_Not_Match_Relationship", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The element does not match original..
        /// </summary>
        internal static string Validation_Element_Not_Match_Original {
            get {
                return ResourceManager.GetString("Validation_Element_Not_Match_Original", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Validation error..
        /// </summary>
        internal static string Validation_Error {
            get {
                return ResourceManager.GetString("Validation_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value(s) of key field(s) have not been provided..
        /// </summary>
        internal static string Validation_Invalid_Key {
            get {
                return ResourceManager.GetString("Validation_Invalid_Key", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None of relationships is available between {0} and {1}..
        /// </summary>
        internal static string Validation_No_Available_Relationship {
            get {
                return ResourceManager.GetString("Validation_No_Available_Relationship", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} of {1} does not match {2} of {3}..
        /// </summary>
        internal static string Validation_RelatedFields_Not_Match {
            get {
                return ResourceManager.GetString("Validation_RelatedFields_Not_Match", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confuse elementName and setName..
        /// </summary>
        internal static string Validation_Schema_Confuse_ElementName_SetName {
            get {
                return ResourceManager.GetString("Validation_Schema_Confuse_ElementName_SetName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duplicate Elements..
        /// </summary>
        internal static string Validation_Schema_Duplicate_Elements {
            get {
                return ResourceManager.GetString("Validation_Schema_Duplicate_Elements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duplicate Sets..
        /// </summary>
        internal static string Validation_Schema_Duplicate_Sets {
            get {
                return ResourceManager.GetString("Validation_Schema_Duplicate_Sets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is not exist..
        /// </summary>
        internal static string Validation_Schema_Not_Exists_Element {
            get {
                return ResourceManager.GetString("Validation_Schema_Not_Exists_Element", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} of {1} is not exist..
        /// </summary>
        internal static string Validation_Schema_Not_Exists_Field {
            get {
                return ResourceManager.GetString("Validation_Schema_Not_Exists_Field", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid &quot;Type&quot; of Relationship..
        /// </summary>
        internal static string Validation_Schema_Relationship_Invalid_Type {
            get {
                return ResourceManager.GetString("Validation_Schema_Relationship_Invalid_Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Navigation field is not allowed for RelationShip..
        /// </summary>
        internal static string Validation_Schema_Relationship_Navigation_Field_Not_Allowed {
            get {
                return ResourceManager.GetString("Validation_Schema_Relationship_Navigation_Field_Not_Allowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Version&quot; is null or empty..
        /// </summary>
        internal static string Version_IsNullOrEmpty {
            get {
                return ResourceManager.GetString("Version_IsNullOrEmpty", resourceCulture);
            }
        }
    }
}
